/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jreyes
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        if_Clientes = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Clientes = new javax.swing.JTable();
        if_Asesores = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Asesores = new javax.swing.JTable();
        if_Baja = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Baja = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenu();
        bdBaja = new javax.swing.JMenuItem();
        bdAsesores = new javax.swing.JMenuItem();
        bdClientes = new javax.swing.JMenuItem();
        opciones = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Panel Administrador");

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        if_Clientes.setClosable(true);
        if_Clientes.setIconifiable(true);
        if_Clientes.setMaximizable(true);
        if_Clientes.setResizable(true);
        if_Clientes.setTitle("Base Datos Clientes");
        if_Clientes.setVisible(false);

        DefaultTableModel modelClientes = new DefaultTableModel();
        tbl_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_Clientes);

        javax.swing.GroupLayout if_ClientesLayout = new javax.swing.GroupLayout(if_Clientes.getContentPane());
        if_Clientes.getContentPane().setLayout(if_ClientesLayout);
        if_ClientesLayout.setHorizontalGroup(
            if_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        if_ClientesLayout.setVerticalGroup(
            if_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        if_Asesores.setClosable(true);
        if_Asesores.setIconifiable(true);
        if_Asesores.setMaximizable(true);
        if_Asesores.setResizable(true);
        if_Asesores.setTitle("Base Datos Asesores");
        if_Asesores.setVisible(false);

        DefaultTableModel modelAsesores = new DefaultTableModel();
        tbl_Asesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_Asesores);

        javax.swing.GroupLayout if_AsesoresLayout = new javax.swing.GroupLayout(if_Asesores.getContentPane());
        if_Asesores.getContentPane().setLayout(if_AsesoresLayout);
        if_AsesoresLayout.setHorizontalGroup(
            if_AsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        if_AsesoresLayout.setVerticalGroup(
            if_AsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        if_Baja.setClosable(true);
        if_Baja.setIconifiable(true);
        if_Baja.setMaximizable(true);
        if_Baja.setResizable(true);
        if_Baja.setTitle("Base Datos Baja");
        if_Baja.setVisible(false);

        DefaultTableModel modelBaja = new DefaultTableModel();
        tbl_Baja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tbl_Baja);

        javax.swing.GroupLayout if_BajaLayout = new javax.swing.GroupLayout(if_Baja.getContentPane());
        if_Baja.getContentPane().setLayout(if_BajaLayout);
        if_BajaLayout.setHorizontalGroup(
            if_BajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        if_BajaLayout.setVerticalGroup(
            if_BajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(if_Clientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(if_Asesores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(if_Baja, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(if_Baja, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(if_Asesores, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(if_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1007, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(if_Asesores, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(if_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(if_Baja, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(459, Short.MAX_VALUE))
        );

        menu.setText("Menu");

        Nuevo.setText("Nuevo");
        menu.add(Nuevo);

        bdBaja.setText("Base Datos Clientes");
        bdBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdBajaActionPerformed(evt);
            }
        });
        menu.add(bdBaja);

        bdAsesores.setText("Base Datos Asesores");
        menu.add(bdAsesores);

        bdClientes.setText("Base Datos Baja");
        menu.add(bdClientes);

        jMenuBar1.add(menu);

        opciones.setText("Opciones");

        salir.setText("Salir");
        opciones.add(salir);

        jMenuBar1.add(opciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bdBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdBajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Nuevo;
    private javax.swing.JMenuItem bdAsesores;
    private javax.swing.JMenuItem bdBaja;
    private javax.swing.JMenuItem bdClientes;
    private javax.swing.JInternalFrame if_Asesores;
    private javax.swing.JInternalFrame if_Baja;
    private javax.swing.JInternalFrame if_Clientes;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu opciones;
    private javax.swing.JMenuItem salir;
    public javax.swing.JTable tbl_Asesores;
    public javax.swing.JTable tbl_Baja;
    public javax.swing.JTable tbl_Clientes;
    // End of variables declaration//GEN-END:variables
}
