/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jreyes
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        
        this.if_Asesores.setVisible(false);
        this.if_Clientes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        if_Clientes = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Clientes = new javax.swing.JTable();
        if_Asesores = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Asesores = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        m_baseGeneralClientes = new javax.swing.JMenuItem();
        m_baseGeneralAsesores = new javax.swing.JMenuItem();
        opciones = new javax.swing.JMenu();
        o_salir = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Panel Administrador");

        jDesktopPane1.setBackground(new java.awt.Color(204, 0, 255));
        jDesktopPane1.setAutoscrolls(true);

        if_Clientes.setClosable(true);
        if_Clientes.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_Clientes.setIconifiable(true);
        if_Clientes.setMaximizable(true);
        if_Clientes.setResizable(true);
        if_Clientes.setTitle("Base Datos Clientes");
        if_Clientes.setVisible(true);

        DefaultTableModel modelClientes = new DefaultTableModel();
        tbl_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_Clientes);

        javax.swing.GroupLayout if_ClientesLayout = new javax.swing.GroupLayout(if_Clientes.getContentPane());
        if_Clientes.getContentPane().setLayout(if_ClientesLayout);
        if_ClientesLayout.setHorizontalGroup(
            if_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        if_ClientesLayout.setVerticalGroup(
            if_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );

        if_Asesores.setClosable(true);
        if_Asesores.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_Asesores.setIconifiable(true);
        if_Asesores.setMaximizable(true);
        if_Asesores.setResizable(true);
        if_Asesores.setTitle("Base Datos Asesores");
        if_Asesores.setVisible(true);

        DefaultTableModel modelAsesores = new DefaultTableModel();
        tbl_Asesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_Asesores);

        javax.swing.GroupLayout if_AsesoresLayout = new javax.swing.GroupLayout(if_Asesores.getContentPane());
        if_Asesores.getContentPane().setLayout(if_AsesoresLayout);
        if_AsesoresLayout.setHorizontalGroup(
            if_AsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );
        if_AsesoresLayout.setVerticalGroup(
            if_AsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(if_Clientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(if_Asesores, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(639, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(if_Asesores)
                    .addComponent(if_Clientes))
                .addGap(28, 28, 28))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(if_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(if_Asesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        menu.setText("Menu");

        Nuevo.setText("Nuevo");

        jMenu1.setText("Nueva Asignacion");
        Nuevo.add(jMenu1);

        jMenu2.setText("Nuevo Formulario");
        Nuevo.add(jMenu2);

        menu.add(Nuevo);

        m_baseGeneralClientes.setText("Base Datos Clientes");
        m_baseGeneralClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_baseGeneralClientesActionPerformed(evt);
            }
        });
        menu.add(m_baseGeneralClientes);

        m_baseGeneralAsesores.setText("Base Datos Asesores");
        menu.add(m_baseGeneralAsesores);

        jMenuBar1.add(menu);

        opciones.setText("Opciones");

        o_salir.setText("Salir");
        opciones.add(o_salir);

        jMenuBar1.add(opciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_baseGeneralClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_baseGeneralClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_baseGeneralClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Nuevo;
    public javax.swing.JInternalFrame if_Asesores;
    public javax.swing.JInternalFrame if_Clientes;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JMenuItem m_baseGeneralAsesores;
    public javax.swing.JMenuItem m_baseGeneralClientes;
    private javax.swing.JMenu menu;
    public javax.swing.JMenuItem o_salir;
    private javax.swing.JMenu opciones;
    public javax.swing.JTable tbl_Asesores;
    public javax.swing.JTable tbl_Clientes;
    // End of variables declaration//GEN-END:variables
}
