/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jreyes
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Area de Trabajo");
                      
            
        this.if_buscarCliente.setVisible(false);
        this.if_buscarAsesor.setVisible(false);
        this.if_baseClientes.setVisible(false);
        this.if_baseAsores.setVisible(false);
        this.if_formulario.setVisible(false);
        this.if_casosAsignados.setVisible(false);
        this.if_RegistroDetallado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        if_buscarCliente = new javax.swing.JInternalFrame();
        jLabel27 = new javax.swing.JLabel();
        bc_txt_valorBuscado = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        bc_tbl_datos = new javax.swing.JTable();
        if_buscarAsesor = new javax.swing.JInternalFrame();
        jLabel26 = new javax.swing.JLabel();
        ba_txt_valorBuscado = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        ba_tbl_datos = new javax.swing.JTable();
        if_baseAsores = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_baseGeneralAsesores = new javax.swing.JTable();
        if_formulario = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        f_txt_buscarCliente = new javax.swing.JTextField();
        f_btn_buscarCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        f_tbl_seguimiento = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        f_txt_tramite = new javax.swing.JTextField();
        f_btn_guardar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        informacion = new javax.swing.JPanel();
        asesor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        f_txt_vendedorNombre = new javax.swing.JTextField();
        f_txt_vendedorContructora = new javax.swing.JTextField();
        f_txt_vendedorTelefono = new javax.swing.JTextField();
        f_txt_vendedorCorreo = new javax.swing.JTextField();
        financiera = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        f_txt_honorarios = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        f_txt_direccionUSA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        f_txt_salario = new javax.swing.JTextField();
        negociacion = new javax.swing.JPanel();
        datos = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        f_txt_nombreCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        f_txt_telefonoCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        f_txt_correoCliente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        f_txt_estadoResidencia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        f_txt_profesion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        f_cb_dpi = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        f_cb_nit = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        f_cb_id = new javax.swing.JComboBox<>();
        f_txt_estadoMigratorio = new javax.swing.JComboBox<>();
        f_txt_tipoPropiedad = new javax.swing.JComboBox<>();
        f_txt_estadoCivil = new javax.swing.JComboBox<>();
        repLegal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        f_txt_repNombre = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        f_txt_repParentezco = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        f_txt_repDireccion = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        f_txt_repTelefono = new javax.swing.JTextField();
        f_txt_repBanco = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        notas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        f_txt_notas = new javax.swing.JTextArea();
        f_cb_nuevo = new javax.swing.JCheckBox();
        f_cb_editar = new javax.swing.JCheckBox();
        f_valor_buscado = new javax.swing.JComboBox<>();
        if_baseClientes = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_baseGeneralClientes = new javax.swing.JTable();
        if_casosAsignados = new javax.swing.JInternalFrame();
        jScrollPane7 = new javax.swing.JScrollPane();
        ca_tbl_datos = new javax.swing.JTable();
        if_RegistroDetallado = new javax.swing.JInternalFrame();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        rd_txt_informacion = new javax.swing.JTextField();
        rd_txt_usuario = new javax.swing.JTextField();
        rd_txt_fecha = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        asesores = new javax.swing.JMenu();
        a_buscarAsesores = new javax.swing.JMenuItem();
        a_baseGeneral = new javax.swing.JMenuItem();
        clientes = new javax.swing.JMenu();
        c_buscarCliente = new javax.swing.JMenuItem();
        c_baseGeneral = new javax.swing.JMenuItem();
        formulario = new javax.swing.JMenu();
        f_AbrirFormulario = new javax.swing.JMenuItem();
        f_casosAsignados = new javax.swing.JMenuItem();
        opciones = new javax.swing.JMenu();
        o_Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Area de Trabajo");

        jScrollPane8.setPreferredSize(new java.awt.Dimension(2000, 1500));

        jDesktopPane1.setBackground(new java.awt.Color(77, 208, 225));
        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(2000, 1500));
        jDesktopPane1.setVerifyInputWhenFocusTarget(false);

        if_buscarCliente.setClosable(true);
        if_buscarCliente.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_buscarCliente.setIconifiable(true);
        if_buscarCliente.setMaximizable(true);
        if_buscarCliente.setResizable(true);
        if_buscarCliente.setTitle("Buscar Cliente");
        if_buscarCliente.setAutoscrolls(true);
        if_buscarCliente.setPreferredSize(new java.awt.Dimension(600, 400));
        if_buscarCliente.setVisible(true);

        jLabel27.setText("Buscar Nombre del Cliente");

        DefaultTableModel modelBuscarCliente = new DefaultTableModel();
        bc_tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(bc_tbl_datos);

        javax.swing.GroupLayout if_buscarClienteLayout = new javax.swing.GroupLayout(if_buscarCliente.getContentPane());
        if_buscarCliente.getContentPane().setLayout(if_buscarClienteLayout);
        if_buscarClienteLayout.setHorizontalGroup(
            if_buscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(if_buscarClienteLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(bc_txt_valorBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane6)
        );
        if_buscarClienteLayout.setVerticalGroup(
            if_buscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(if_buscarClienteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(if_buscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(if_buscarClienteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel27))
                    .addComponent(bc_txt_valorBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        if_buscarAsesor.setClosable(true);
        if_buscarAsesor.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_buscarAsesor.setIconifiable(true);
        if_buscarAsesor.setMaximizable(true);
        if_buscarAsesor.setResizable(true);
        if_buscarAsesor.setTitle("Buscar Asesor");
        if_buscarAsesor.setPreferredSize(new java.awt.Dimension(600, 400));
        if_buscarAsesor.setVisible(true);

        jLabel26.setText("Buscar Nombre del Asesor");

        DefaultTableModel modelBuscarAsesores = new DefaultTableModel();
        ba_tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(ba_tbl_datos);

        javax.swing.GroupLayout if_buscarAsesorLayout = new javax.swing.GroupLayout(if_buscarAsesor.getContentPane());
        if_buscarAsesor.getContentPane().setLayout(if_buscarAsesorLayout);
        if_buscarAsesorLayout.setHorizontalGroup(
            if_buscarAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(if_buscarAsesorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(ba_txt_valorBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        if_buscarAsesorLayout.setVerticalGroup(
            if_buscarAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(if_buscarAsesorLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(if_buscarAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(if_buscarAsesorLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel26))
                    .addComponent(ba_txt_valorBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        if_baseAsores.setClosable(true);
        if_baseAsores.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_baseAsores.setIconifiable(true);
        if_baseAsores.setMaximizable(true);
        if_baseAsores.setResizable(true);
        if_baseAsores.setTitle("Base General Asesores");
        if_baseAsores.setPreferredSize(new java.awt.Dimension(600, 400));
        if_baseAsores.setVisible(true);

        tbl_baseGeneralAsesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        DefaultTableModel modelAsesores = new DefaultTableModel();
        jScrollPane2.setViewportView(tbl_baseGeneralAsesores);

        javax.swing.GroupLayout if_baseAsoresLayout = new javax.swing.GroupLayout(if_baseAsores.getContentPane());
        if_baseAsores.getContentPane().setLayout(if_baseAsoresLayout);
        if_baseAsoresLayout.setHorizontalGroup(
            if_baseAsoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        if_baseAsoresLayout.setVerticalGroup(
            if_baseAsoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        if_formulario.setClosable(true);
        if_formulario.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_formulario.setIconifiable(true);
        if_formulario.setResizable(true);
        if_formulario.setTitle("Formulario");
        if_formulario.setPreferredSize(new java.awt.Dimension(600, 900));
        if_formulario.setVisible(true);

        jLabel1.setText("Buscar Cliente");

        f_btn_buscarCliente.setText("Buscar");

        DefaultTableModel modelSeguimiento = new DefaultTableModel();
        f_tbl_seguimiento.setAutoCreateRowSorter(true);
        f_tbl_seguimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        f_tbl_seguimiento.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(f_tbl_seguimiento);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Clase Tramite");

        f_txt_tramite.setEditable(false);

        f_btn_guardar.setText("Guardar");
        f_btn_guardar.setEnabled(false);

        asesor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Asesor"));

        jLabel3.setText("Nombre");

        jLabel4.setText("Constructora");

        jLabel5.setText("Telefono");

        jLabel6.setText("Correo Electronico");

        f_txt_vendedorNombre.setEditable(false);

        f_txt_vendedorContructora.setEditable(false);

        f_txt_vendedorTelefono.setEditable(false);

        f_txt_vendedorCorreo.setEditable(false);

        javax.swing.GroupLayout asesorLayout = new javax.swing.GroupLayout(asesor);
        asesor.setLayout(asesorLayout);
        asesorLayout.setHorizontalGroup(
            asesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asesorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(asesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f_txt_vendedorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(f_txt_vendedorContructora))
                .addGroup(asesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(asesorLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel5))
                    .addGroup(asesorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(asesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_txt_vendedorCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(f_txt_vendedorTelefono))
                .addContainerGap())
        );
        asesorLayout.setVerticalGroup(
            asesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asesorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(f_txt_vendedorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(f_txt_vendedorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(asesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(f_txt_vendedorContructora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(f_txt_vendedorCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        financiera.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Financiera"));

        jLabel7.setText("Honorarios $/Q");

        f_txt_honorarios.setEditable(false);

        jLabel8.setText("Direccion USA");

        f_txt_direccionUSA.setEditable(false);
        f_txt_direccionUSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_txt_direccionUSAActionPerformed(evt);
            }
        });

        jLabel9.setText("Salario $");

        f_txt_salario.setEditable(false);

        javax.swing.GroupLayout financieraLayout = new javax.swing.GroupLayout(financiera);
        financiera.setLayout(financieraLayout);
        financieraLayout.setHorizontalGroup(
            financieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financieraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(financieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(financieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(f_txt_honorarios, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(f_txt_salario))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_txt_direccionUSA)
                .addContainerGap())
        );
        financieraLayout.setVerticalGroup(
            financieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financieraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(financieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(f_txt_honorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(f_txt_direccionUSA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(financieraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(f_txt_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout informacionLayout = new javax.swing.GroupLayout(informacion);
        informacion.setLayout(informacionLayout);
        informacionLayout.setHorizontalGroup(
            informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(financiera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        informacionLayout.setVerticalGroup(
            informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionLayout.createSequentialGroup()
                .addComponent(asesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(financiera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informacion", informacion);

        datos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos"));

        jLabel10.setText("Nombre Cliente");

        f_txt_nombreCliente.setEditable(false);

        jLabel11.setText("Tipo de Propiedad");

        jLabel12.setText("Telefonos");

        f_txt_telefonoCliente.setEditable(false);

        jLabel13.setText("Correo Electonico");

        f_txt_correoCliente.setEditable(false);

        jLabel14.setText("Estado Residencia");

        f_txt_estadoResidencia.setEditable(false);

        jLabel15.setText("Estado Civil");

        jLabel16.setText("Estado Migratorio");

        jLabel17.setText("Profesion");

        f_txt_profesion.setEditable(false);

        jLabel18.setText("DPI?");

        f_cb_dpi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Si", "No" }));

        jLabel19.setText("NIT?");

        f_cb_nit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Si", "No" }));

        jLabel20.setText("ID?");

        f_cb_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Si", "No" }));

        f_txt_estadoMigratorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Residente", "Ciudadano", "Regular" }));

        f_txt_tipoPropiedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Apartamento", "Casa", "Oficina", "Terreno" }));

        f_txt_estadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Casado (a)", "Divorlciado (a)", "Soltero (a)", "Viudo (a)" }));

        javax.swing.GroupLayout datosLayout = new javax.swing.GroupLayout(datos);
        datos.setLayout(datosLayout);
        datosLayout.setHorizontalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel18))
                    .addGroup(datosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(datosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosLayout.createSequentialGroup()
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f_txt_telefonoCliente)
                            .addComponent(f_txt_estadoResidencia)
                            .addComponent(f_txt_estadoMigratorio, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f_txt_nombreCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(datosLayout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(2, 2, 2))
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel17)))
                            .addGroup(datosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(f_txt_tipoPropiedad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f_txt_estadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f_txt_correoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f_txt_profesion, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(datosLayout.createSequentialGroup()
                        .addComponent(f_cb_dpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f_cb_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f_cb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 186, Short.MAX_VALUE)))
                .addContainerGap())
        );
        datosLayout.setVerticalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(f_txt_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(f_txt_tipoPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosLayout.createSequentialGroup()
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(f_txt_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f_txt_correoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(f_txt_estadoResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f_txt_estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(f_txt_profesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f_txt_estadoMigratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(f_cb_dpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(f_cb_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(f_cb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout negociacionLayout = new javax.swing.GroupLayout(negociacion);
        negociacion.setLayout(negociacionLayout);
        negociacionLayout.setHorizontalGroup(
            negociacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        negociacionLayout.setVerticalGroup(
            negociacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, negociacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Negociacion", negociacion);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Representante Legal"));

        jLabel21.setText("Nombre");

        f_txt_repNombre.setEditable(false);

        jLabel22.setText("Parentezco");

        f_txt_repParentezco.setEditable(false);

        jLabel23.setText("Direccion");

        f_txt_repDireccion.setEditable(false);

        jLabel24.setText("Telefono");

        f_txt_repTelefono.setEditable(false);

        f_txt_repBanco.setEditable(false);

        jLabel25.setText("Entidad Bancaria");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(f_txt_repNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_txt_repParentezco, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_txt_repDireccion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_txt_repTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f_txt_repBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(f_txt_repNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(f_txt_repParentezco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(f_txt_repDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(f_txt_repTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_txt_repBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout repLegalLayout = new javax.swing.GroupLayout(repLegal);
        repLegal.setLayout(repLegalLayout);
        repLegalLayout.setHorizontalGroup(
            repLegalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        repLegalLayout.setVerticalGroup(
            repLegalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repLegalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Representante Legal", repLegal);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Notas Extras"));

        f_txt_notas.setEditable(false);
        f_txt_notas.setColumns(20);
        f_txt_notas.setRows(5);
        jScrollPane4.setViewportView(f_txt_notas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout notasLayout = new javax.swing.GroupLayout(notas);
        notas.setLayout(notasLayout);
        notasLayout.setHorizontalGroup(
            notasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        notasLayout.setVerticalGroup(
            notasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Notas", notas);

        f_cb_nuevo.setText("Nuevo");

        f_cb_editar.setText("Editar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(f_txt_tramite, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(f_btn_guardar)
                .addGap(18, 18, 18)
                .addComponent(f_cb_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(f_cb_nuevo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(f_txt_tramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_btn_guardar)
                    .addComponent(f_cb_nuevo)
                    .addComponent(f_cb_editar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        f_valor_buscado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Nombre", "Telefono", "Correo" }));

        javax.swing.GroupLayout if_formularioLayout = new javax.swing.GroupLayout(if_formulario.getContentPane());
        if_formulario.getContentPane().setLayout(if_formularioLayout);
        if_formularioLayout.setHorizontalGroup(
            if_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(if_formularioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(f_valor_buscado, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(f_txt_buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(f_btn_buscarCliente)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        if_formularioLayout.setVerticalGroup(
            if_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(if_formularioLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(if_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(if_formularioLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(if_formularioLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(f_valor_buscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(if_formularioLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(f_txt_buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(f_btn_buscarCliente))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
        );

        if_baseClientes.setClosable(true);
        if_baseClientes.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_baseClientes.setIconifiable(true);
        if_baseClientes.setMaximizable(true);
        if_baseClientes.setResizable(true);
        if_baseClientes.setTitle("Base General Clientes");
        if_baseClientes.setPreferredSize(new java.awt.Dimension(600, 400));
        if_baseClientes.setVisible(true);

        DefaultTableModel modelClientes = new DefaultTableModel();
        tbl_baseGeneralClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_baseGeneralClientes);

        javax.swing.GroupLayout if_baseClientesLayout = new javax.swing.GroupLayout(if_baseClientes.getContentPane());
        if_baseClientes.getContentPane().setLayout(if_baseClientesLayout);
        if_baseClientesLayout.setHorizontalGroup(
            if_baseClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        if_baseClientesLayout.setVerticalGroup(
            if_baseClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        if_casosAsignados.setClosable(true);
        if_casosAsignados.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_casosAsignados.setIconifiable(true);
        if_casosAsignados.setResizable(true);
        if_casosAsignados.setTitle("Casos Asignados");
        if_casosAsignados.setPreferredSize(new java.awt.Dimension(800, 400));
        if_casosAsignados.setVisible(true);

        DefaultTableModel modelCasosAsignados = new DefaultTableModel();
        ca_tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(ca_tbl_datos);

        javax.swing.GroupLayout if_casosAsignadosLayout = new javax.swing.GroupLayout(if_casosAsignados.getContentPane());
        if_casosAsignados.getContentPane().setLayout(if_casosAsignadosLayout);
        if_casosAsignadosLayout.setHorizontalGroup(
            if_casosAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        if_casosAsignadosLayout.setVerticalGroup(
            if_casosAsignadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        if_RegistroDetallado.setClosable(true);
        if_RegistroDetallado.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if_RegistroDetallado.setIconifiable(true);
        if_RegistroDetallado.setResizable(true);
        if_RegistroDetallado.setTitle("Registro Detallado");
        if_RegistroDetallado.setPreferredSize(new java.awt.Dimension(380, 165));
        if_RegistroDetallado.setVisible(true);

        jLabel28.setText("Fecha");

        jLabel29.setText("Usuario");

        jLabel30.setText("Informacion");

        rd_txt_usuario.setEnabled(false);

        rd_txt_fecha.setEnabled(false);

        javax.swing.GroupLayout if_RegistroDetalladoLayout = new javax.swing.GroupLayout(if_RegistroDetallado.getContentPane());
        if_RegistroDetallado.getContentPane().setLayout(if_RegistroDetalladoLayout);
        if_RegistroDetalladoLayout.setHorizontalGroup(
            if_RegistroDetalladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(if_RegistroDetalladoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(if_RegistroDetalladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(if_RegistroDetalladoLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(38, 38, 38)
                        .addComponent(rd_txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(if_RegistroDetalladoLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(31, 31, 31)
                        .addComponent(rd_txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(if_RegistroDetalladoLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(10, 10, 10)
                        .addComponent(rd_txt_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        if_RegistroDetalladoLayout.setVerticalGroup(
            if_RegistroDetalladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(if_RegistroDetalladoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(if_RegistroDetalladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(if_RegistroDetalladoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel28))
                    .addComponent(rd_txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(if_RegistroDetalladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(if_RegistroDetalladoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel29))
                    .addComponent(rd_txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(if_RegistroDetalladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(if_RegistroDetalladoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel30))
                    .addComponent(rd_txt_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(if_buscarCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(if_buscarAsesor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(if_baseAsores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(if_formulario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(if_baseClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(if_casosAsignados, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(if_RegistroDetallado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(if_casosAsignados, javax.swing.GroupLayout.PREFERRED_SIZE, 1286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(if_formulario, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(if_buscarAsesor, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                                    .addComponent(if_buscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(if_baseClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(if_baseAsores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(77, Short.MAX_VALUE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(if_RegistroDetallado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(if_RegistroDetallado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(if_baseAsores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(if_buscarAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(if_baseClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(if_buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(if_formulario, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(if_casosAsignados, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        jScrollPane8.setViewportView(jDesktopPane1);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(114, 769));

        archivo.setText("Archivos");

        asesores.setText("Asesores");

        a_buscarAsesores.setText("Buscar Asesor");
        asesores.add(a_buscarAsesores);

        a_baseGeneral.setText("Base General");
        asesores.add(a_baseGeneral);

        archivo.add(asesores);

        clientes.setText("Clientes");

        c_buscarCliente.setText("Buscar Cliente");
        clientes.add(c_buscarCliente);

        c_baseGeneral.setText("Base General");
        clientes.add(c_baseGeneral);

        archivo.add(clientes);

        formulario.setText("Formulario");

        f_AbrirFormulario.setText("Abrir Formulario");
        formulario.add(f_AbrirFormulario);

        f_casosAsignados.setText("Casos asignados");
        formulario.add(f_casosAsignados);

        archivo.add(formulario);

        jMenuBar1.add(archivo);

        opciones.setText("Opciones");

        o_Salir.setText("Cerrar Sesion");
        opciones.add(o_Salir);

        jMenuBar1.add(opciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 2007, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_txt_direccionUSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_txt_direccionUSAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_txt_direccionUSAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem a_baseGeneral;
    public javax.swing.JMenuItem a_buscarAsesores;
    public javax.swing.JMenu archivo;
    private javax.swing.JPanel asesor;
    public javax.swing.JMenu asesores;
    public javax.swing.JTable ba_tbl_datos;
    public javax.swing.JTextField ba_txt_valorBuscado;
    public javax.swing.JTable bc_tbl_datos;
    public javax.swing.JTextField bc_txt_valorBuscado;
    public javax.swing.JMenuItem c_baseGeneral;
    public javax.swing.JMenuItem c_buscarCliente;
    public javax.swing.JTable ca_tbl_datos;
    public javax.swing.JMenu clientes;
    private javax.swing.JPanel datos;
    public javax.swing.JMenuItem f_AbrirFormulario;
    public javax.swing.JButton f_btn_buscarCliente;
    public javax.swing.JButton f_btn_guardar;
    public javax.swing.JMenuItem f_casosAsignados;
    public javax.swing.JComboBox<String> f_cb_dpi;
    public javax.swing.JCheckBox f_cb_editar;
    public javax.swing.JComboBox<String> f_cb_id;
    public javax.swing.JComboBox<String> f_cb_nit;
    public javax.swing.JCheckBox f_cb_nuevo;
    public javax.swing.JTable f_tbl_seguimiento;
    public javax.swing.JTextField f_txt_buscarCliente;
    public javax.swing.JTextField f_txt_correoCliente;
    public javax.swing.JTextField f_txt_direccionUSA;
    public javax.swing.JComboBox<String> f_txt_estadoCivil;
    public javax.swing.JComboBox<String> f_txt_estadoMigratorio;
    public javax.swing.JTextField f_txt_estadoResidencia;
    public javax.swing.JTextField f_txt_honorarios;
    public javax.swing.JTextField f_txt_nombreCliente;
    public javax.swing.JTextArea f_txt_notas;
    public javax.swing.JTextField f_txt_profesion;
    public javax.swing.JTextField f_txt_repBanco;
    public javax.swing.JTextField f_txt_repDireccion;
    public javax.swing.JTextField f_txt_repNombre;
    public javax.swing.JTextField f_txt_repParentezco;
    public javax.swing.JTextField f_txt_repTelefono;
    public javax.swing.JTextField f_txt_salario;
    public javax.swing.JTextField f_txt_telefonoCliente;
    public javax.swing.JComboBox<String> f_txt_tipoPropiedad;
    public javax.swing.JTextField f_txt_tramite;
    public javax.swing.JTextField f_txt_vendedorContructora;
    public javax.swing.JTextField f_txt_vendedorCorreo;
    public javax.swing.JTextField f_txt_vendedorNombre;
    public javax.swing.JTextField f_txt_vendedorTelefono;
    public javax.swing.JComboBox<String> f_valor_buscado;
    private javax.swing.JPanel financiera;
    public javax.swing.JMenu formulario;
    public javax.swing.JInternalFrame if_RegistroDetallado;
    public javax.swing.JInternalFrame if_baseAsores;
    public javax.swing.JInternalFrame if_baseClientes;
    public javax.swing.JInternalFrame if_buscarAsesor;
    public javax.swing.JInternalFrame if_buscarCliente;
    public javax.swing.JInternalFrame if_casosAsignados;
    public javax.swing.JInternalFrame if_formulario;
    private javax.swing.JPanel informacion;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel negociacion;
    private javax.swing.JPanel notas;
    public javax.swing.JMenuItem o_Salir;
    public javax.swing.JMenu opciones;
    public javax.swing.JTextField rd_txt_fecha;
    public javax.swing.JTextField rd_txt_informacion;
    public javax.swing.JTextField rd_txt_usuario;
    private javax.swing.JPanel repLegal;
    public javax.swing.JTable tbl_baseGeneralAsesores;
    public javax.swing.JTable tbl_baseGeneralClientes;
    // End of variables declaration//GEN-END:variables
}
